development:
  adapter: postgresql
  database: reportbooru 
  pool: 5

test:
  adapter: postgresql
  database: reportbooru_test
  pool: 5

production:
  adapter: postgresql
  database: reportbooru
  pool: 5

danbooru_development:
  adapter: postgresql
  database: danbooru2

danbooru_production:
  adapter: postgresql
  database: danbooru2
  username: danbooru
  host: localhost
  password: <%= ENV["DANBOORU_RO_PASSWORD"] %>

archive_development:
  adapter: postgresql
  database: archive_development

archive_production:
  adapter: postgresql
  database: <%= ENV["ARCHIVE_DB"] %>
  username: <%= ENV["ARCHIVE_DB_USER"] %>
  host: <%= ENV["ARCHIVE_DB_HOST"] %>
  password: <%= ENV["ARCHIVE_DB_PASSWORD"] %>
